version: '2.1'

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Checkstyle
          command: mvn checkstyle:checkstyle
      - add_ssh_keys:
          fingerprints:
            - SHA256:psG85UZdKz/erk/dzHnrS7YMehGGHEY57pFUDrWIQ0E
      - run:
          name: Badges
          command: |
            mvn post-site
            git config user.email "yacinetrousselle@gmail.com"
            git config user.name "Yacine Trousselle"
            git add badges
            git commit -m "[skip ci] Update checkstyle badge"
            git push
  test:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          name: Test
          command: mvn test
      - codecov/upload
  javadoc:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          name: Javadoc
          command: mvn javadoc:javadoc
      - add_ssh_keys:
          fingerprints:
            - SHA256:psG85UZdKz/erk/dzHnrS7YMehGGHEY57pFUDrWIQ0E
      - run:
          name: Push to gh-pages branch
          command: |
            git config user.email "yacinetrousselle@gmail.com"
            git config user.name "Yacine Trousselle"
            mv docs/apidocs new_docs
            git checkout gh-pages
            rm -fr docs
            mv new_docs docs
            touch docs/.nojekyll
            git add docs
            git commit -m "[skip ci] Deploy javadoc"
            git push

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - javadoc:
          requires:
            - test
