version: '2.1'

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
  test:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          name: Test
          command: mvn test
      - codecov/upload
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
