version: '2.1'



jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
  test:
    docker:
      - image: cimg/openjdk
    steps:
      - checkout
      - run:
          name: Test
          command: mvn test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
