version: '2.1'

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Checkstyle
          command: mvn checkstyle:checkstyle
  test:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          name: Test
          command: mvn test
      - codecov/upload
  javadoc:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          name: Javadoc
          command: mvn javadoc:javadoc
      - persist_to_workspace:
          root: .
          paths:
            - docs
  publish:
    docker:
      - image: node:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages
            git config user.email "yacinetrousselle@gmail.com"
            git config user.name "Yacine Trousselle"
      - add_ssh_keys:
          fingerprints:
            - SHA256:psG85UZdKz/erk/dzHnrS7YMehGGHEY57pFUDrWIQ0E
      - run:
          name: Deploy docs to gh-pages branch
          command: npx gh-pages --message "Update docs [skip ci]"  --dist docs/apidocs/

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - javadoc:
          requires:
            - test
      - publish:
          requires:
            - javadoc
